// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: stocks/stocks.proto

package stocks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StocksServiceClient is the client API for StocksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StocksServiceClient interface {
	GetLastPrice(ctx context.Context, in *StockSymbolMessage, opts ...grpc.CallOption) (*StockPriceMessage, error)
	GetPriceAtDate(ctx context.Context, in *PriceAtDateMessage, opts ...grpc.CallOption) (*StockPriceMessage, error)
}

type stocksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStocksServiceClient(cc grpc.ClientConnInterface) StocksServiceClient {
	return &stocksServiceClient{cc}
}

func (c *stocksServiceClient) GetLastPrice(ctx context.Context, in *StockSymbolMessage, opts ...grpc.CallOption) (*StockPriceMessage, error) {
	out := new(StockPriceMessage)
	err := c.cc.Invoke(ctx, "/stocks.StocksService/GetLastPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stocksServiceClient) GetPriceAtDate(ctx context.Context, in *PriceAtDateMessage, opts ...grpc.CallOption) (*StockPriceMessage, error) {
	out := new(StockPriceMessage)
	err := c.cc.Invoke(ctx, "/stocks.StocksService/GetPriceAtDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StocksServiceServer is the server API for StocksService service.
// All implementations must embed UnimplementedStocksServiceServer
// for forward compatibility
type StocksServiceServer interface {
	GetLastPrice(context.Context, *StockSymbolMessage) (*StockPriceMessage, error)
	GetPriceAtDate(context.Context, *PriceAtDateMessage) (*StockPriceMessage, error)
	mustEmbedUnimplementedStocksServiceServer()
}

// UnimplementedStocksServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStocksServiceServer struct {
}

func (UnimplementedStocksServiceServer) GetLastPrice(context.Context, *StockSymbolMessage) (*StockPriceMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastPrice not implemented")
}
func (UnimplementedStocksServiceServer) GetPriceAtDate(context.Context, *PriceAtDateMessage) (*StockPriceMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPriceAtDate not implemented")
}
func (UnimplementedStocksServiceServer) mustEmbedUnimplementedStocksServiceServer() {}

// UnsafeStocksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StocksServiceServer will
// result in compilation errors.
type UnsafeStocksServiceServer interface {
	mustEmbedUnimplementedStocksServiceServer()
}

func RegisterStocksServiceServer(s grpc.ServiceRegistrar, srv StocksServiceServer) {
	s.RegisterService(&StocksService_ServiceDesc, srv)
}

func _StocksService_GetLastPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockSymbolMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StocksServiceServer).GetLastPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stocks.StocksService/GetLastPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StocksServiceServer).GetLastPrice(ctx, req.(*StockSymbolMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _StocksService_GetPriceAtDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceAtDateMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StocksServiceServer).GetPriceAtDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stocks.StocksService/GetPriceAtDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StocksServiceServer).GetPriceAtDate(ctx, req.(*PriceAtDateMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// StocksService_ServiceDesc is the grpc.ServiceDesc for StocksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StocksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stocks.StocksService",
	HandlerType: (*StocksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastPrice",
			Handler:    _StocksService_GetLastPrice_Handler,
		},
		{
			MethodName: "GetPriceAtDate",
			Handler:    _StocksService_GetPriceAtDate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stocks/stocks.proto",
}
