// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: stocks/stocks.proto

package stocks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockSymbolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *StockSymbolMessage) Reset() {
	*x = StockSymbolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stocks_stocks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockSymbolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockSymbolMessage) ProtoMessage() {}

func (x *StockSymbolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockSymbolMessage.ProtoReflect.Descriptor instead.
func (*StockSymbolMessage) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{0}
}

func (x *StockSymbolMessage) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type StockPriceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float32 `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *StockPriceMessage) Reset() {
	*x = StockPriceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stocks_stocks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockPriceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockPriceMessage) ProtoMessage() {}

func (x *StockPriceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockPriceMessage.ProtoReflect.Descriptor instead.
func (*StockPriceMessage) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{1}
}

func (x *StockPriceMessage) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type PriceAtDateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Date   string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *PriceAtDateMessage) Reset() {
	*x = PriceAtDateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stocks_stocks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceAtDateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceAtDateMessage) ProtoMessage() {}

func (x *PriceAtDateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_stocks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceAtDateMessage.ProtoReflect.Descriptor instead.
func (*PriceAtDateMessage) Descriptor() ([]byte, []int) {
	return file_stocks_stocks_proto_rawDescGZIP(), []int{2}
}

func (x *PriceAtDateMessage) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceAtDateMessage) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_stocks_stocks_proto protoreflect.FileDescriptor

var file_stocks_stocks_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x2c, 0x0a,
	0x12, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x29, 0x0a, 0x11, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x40, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x32, 0xa3, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x2e,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_stocks_stocks_proto_rawDescOnce sync.Once
	file_stocks_stocks_proto_rawDescData = file_stocks_stocks_proto_rawDesc
)

func file_stocks_stocks_proto_rawDescGZIP() []byte {
	file_stocks_stocks_proto_rawDescOnce.Do(func() {
		file_stocks_stocks_proto_rawDescData = protoimpl.X.CompressGZIP(file_stocks_stocks_proto_rawDescData)
	})
	return file_stocks_stocks_proto_rawDescData
}

var file_stocks_stocks_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stocks_stocks_proto_goTypes = []interface{}{
	(*StockSymbolMessage)(nil), // 0: stocks.StockSymbolMessage
	(*StockPriceMessage)(nil),  // 1: stocks.StockPriceMessage
	(*PriceAtDateMessage)(nil), // 2: stocks.PriceAtDateMessage
}
var file_stocks_stocks_proto_depIdxs = []int32{
	0, // 0: stocks.StocksService.GetLastPrice:input_type -> stocks.StockSymbolMessage
	2, // 1: stocks.StocksService.GetPriceAtDate:input_type -> stocks.PriceAtDateMessage
	1, // 2: stocks.StocksService.GetLastPrice:output_type -> stocks.StockPriceMessage
	1, // 3: stocks.StocksService.GetPriceAtDate:output_type -> stocks.StockPriceMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stocks_stocks_proto_init() }
func file_stocks_stocks_proto_init() {
	if File_stocks_stocks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stocks_stocks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockSymbolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stocks_stocks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockPriceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stocks_stocks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceAtDateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stocks_stocks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stocks_stocks_proto_goTypes,
		DependencyIndexes: file_stocks_stocks_proto_depIdxs,
		MessageInfos:      file_stocks_stocks_proto_msgTypes,
	}.Build()
	File_stocks_stocks_proto = out.File
	file_stocks_stocks_proto_rawDesc = nil
	file_stocks_stocks_proto_goTypes = nil
	file_stocks_stocks_proto_depIdxs = nil
}
